[1.18.2] Add Traditional Chinese Language
CoFH/ThermalFoundation pull request #42
Opened 2022-11-26 09:49 UTC by Jimmy-sheep

Add Traditional Chinese Language, copy from zh_cn.json, but change 5%-10% of phraseology.

2022-11-26 20:46 UTC, StarskyXIII commented
一堆未在地化的內容，請確實與原版翻譯對照後再進行 PR。
10% 的用語是指繁化姬轉換的嗎？

2022-11-27 05:38 UTC, Jimmy-sheep commented
> 一堆未在地化的內容，請確實與原版翻譯對照後再進行 PR。 10% 的用語是指繁化姬轉換的嗎？ 連遊戲都沒打開測試過？

這是給1.18.2版本使用的 對照en_us語言 我想應該是沒有遺漏什麼 用語部份是我自己純手動用Notepad++更改的並不是用機翻 (我在此之前也沒聽過繁化姬) 也許有些部分會遺漏 也有些兩岸用語我搞混而沒翻到 可以提出來我會再修正
這也因為和朋友玩後看到1.18.2版本沒有繁體中文而第一次嘗試自己翻譯 所以有些格式不一定能夠符合要求

2022-11-27 06:24 UTC, StarskyXIII requested changes

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.apatite_block": "磷灰石塊",
該類型方塊，原版幾乎都是譯作為 `OO方塊`，看你要不要參考看看

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.enderium_block": "終界塊",
這邊只是建議，由於有多款模組分別加入了 `End` `Ender` 之類的金屬，
故為了做出區別，這邊可以譯作 `終界合金`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.orange_rockwool": "橘色石棉",
Orange 原版譯作 `橙色`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.chiseled_rich_slag": "鑿製富爐渣塊",
Chiseled 原版譯作 `浮雕`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.polished_rich_slag": "燒製富爐渣塊",
Polished 原版譯作 `拋光`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "death.attack.basalz": "%1$s的世界天翻地覆！",
變數為玩家名時，建議與中文字間留空格

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "entity.thermal.basalz": "岩石人",
Blaze 原版譯作 `烈焰使者`，這邊 `人` 改譯作 `使者` 是否比較妥當呢？

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "info.thermal.lock.use": "對可兼容方塊使用來為其上鎖。",
相容

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.syrup_bottle": "瓶裝糖漿",
與蜂蜜瓶類似，翻成 `糖漿瓶` 應該比較好

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.cinnabar": "朱砂",
硃砂

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.basalz_spawn_egg": "岩石人刷怪蛋",
參考格式：`岩石使者 生怪蛋`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.raw_lead": "粗鉛",
原版譯作 `O原礦`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.invar_coin": "殷鋼幣",
台灣這邊沒 `殷鋼` 的用法，建議改譯作 `不變鋼`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "subtitles.thermal.entity.basalz.ambient": "岩石人呼吸",
Blaze 原版譯作 `烈焰使者`，這邊 `人` 改譯作 `使者` 是否比較妥當呢？

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.enderium_coin": "終界幣",
這邊只是建議，由於有多款模組分別加入了 `End` `Ender` 之類的金屬，
故為了做出區別，這邊可以譯作 `終界合金`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "info.thermal.augment.attr.RFXfer": "RF傳輸",
英文與中文間建議留空格

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.fluid_tank_creative_augment": "創造儲罐建構",
Creative 建議譯作 `創造模式`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.machine_speed_augment.desc": "以RF效率降低為代價提升處理速度。",
英文與中文間建議留空格

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.side_config_augment": "模塊設置重構",
`Module` 台灣這邊說法是 `模組`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.hazmat_helmet": "防護盔",
個人感覺盔甲照原版格式翻譯會比較合適，也更方便玩家在 JEI 搜尋相同類型東西
`頭盔` `胸甲` `護腿` `靴子`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.gunpowder_block": "壓實火藥塊",
不太理解為何會冒出 `壓實`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.charcoal_block": "木炭塊",
該類型方塊，原版幾乎都是譯作為 `OO方塊`，看你要不要參考看看

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.raw_lead_block": "粗鉛塊",
原版譯作為 `O原礦方塊`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.earth_tnt.keyword": "岩石人 地 tnt",
Blaze 原版譯作 `烈焰使者`，這邊 `人` 改譯作 `使者` 是否比較妥當呢？

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.chunk_loader.keyword": "區塊 區塊加載器 加載器",
載入

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "death.attack.sadiroot": "%1$s被薩蒂根莖的刺葉扎死了",
變數為玩家名時，建議與中文字間留空格

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.dough": "面團",
麵團...

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.energy_distributor": "RF分發接口",
接口，台灣這邊說法是 `介面`
雖然這模組還沒有發布，但這翻譯真的很奇怪，看你要不要修改一下

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "info.thermal.item_buffer.2": "鎖存模式下，只有所有物品均滿足要求才會輸出。",
鎖存，台灣這邊說法是 `閂鎖`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.slot_seal": "槽楔",
~~感覺有點太文青了~~，我無法想像玩家交談時，「槽楔」「槽楔」的唸

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.slot_seal.desc": "防止所在槽位被使用。適用於有多個輸入槽的機器。",
原版 Slot 會譯作為 `欄位`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.lumium_activator_rail": "流明激活鐵軌",
`Activator Rail` 原版翻 `觸發鐵軌`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.prismarine_activator_rail": "海晶激活鐵軌",
原版譯作 `海磷`

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "entity.thermal.phyto_tnt_minecart": "PNT礦車",
英文建議與中文間留空

2022-11-27 06:24 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.earth_tnt_minecart.keyword": "岩石人 地 tnt",
Blaze 原版譯作 `烈焰使者`，這邊 `人` 改譯作 `使者` 是否比較妥當呢？

2022-11-27 07:20 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.enderium_block": "終界塊",
> 這邊可以譯作 `終界合金`

感謝你的建議 我朋友說以前似乎翻譯叫做`諧振終界` 我剛查看後發現它的流體形式似乎也沿用了這個舊名稱 這邊我覺得也許可以更改方塊跟流體的翻譯 變成`諧振合金`呢? 既保留了部分舊名稱 也明確顯示了他是種金屬
不過我不確定這樣是否會跟其他模組有相似的名稱...

2022-11-27 07:22 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.orange_rockwool": "橘色石棉",
抱歉這是我的失誤 我誤記成原版是橘色

2022-11-27 09:55 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.enderium_block": "終界塊",
我個人對舊版本接觸較少，但根據我查閱的對岸資料（早期台灣翻譯幾乎都為直接簡繁轉換而來），
https://www.mcmod.cn/item/9425.html
該金屬原先就稱作為 `Enderium Ingot`，也就是 `終界錠`。
諧振終界 `Resonant Ender` 為流體專屬的特殊名稱，
類似特殊的命名還有不穩定紅石 `Destabilized Redstone`（將紅石送入熔岩爐熔化）。
故我對將錠與流體統一命名為 `諧振` 持保留的態度。

2022-11-27 10:01 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.energy_distributor": "RF分發接口",
> 接口，台灣這邊說法是 `介面` 雖然這模組還沒有發布，但這翻譯真的很奇怪，看你要不要修改一下

這部分我在想...也許翻成`埠`更合適?

2022-11-27 10:05 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.slot_seal": "槽楔",
> ~感覺有點太文青了~，我無法想像玩家交談時，「槽楔」「槽楔」的唸

確實 但這物品確實更接近"楔子"這種東西...
又或者是翻譯成`欄位卡榫`呢...?

2022-11-28 19:38 UTC, StarskyXIII requested changes

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.sawdust_block": "壓實鋸屑方塊",
壓實感覺是多餘的

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "info.thermal.lock.use": "對可相容方塊使用為其上鎖。",
`可` 感覺是贅字

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "info.thermal.satchel.use.sneak": "潛行並使用以打開物品篩選界面。",
台灣這邊應用 `介面`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.detonator": "遙控起爆器",
引爆器是否會更合適

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.machine_speed_augment": "通量鏈接放大器",
台灣這邊應用 `連結`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.lightning_tnt.desc": "震擊一大片區域，起效時有很大機率伴有雷電。",
`起作用` 或 `生效` 會不會比較合適

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.redstone_tnt": "紅石發信炸藥",
這邊我不太肯定，但台灣這邊應該是使用 `發射` 或 `訊號發射`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "info.thermal.device_nullifier.2": "手動輸入的物品必須通過點擊按鈕進行銷毀。",
通過是指你行經一個地方，應用 `透過`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "info.thermal.machine_centrifuge.0": "通過高速旋轉離心技術將物品分離成其構成材料。",
通過是指你行經一個地方，應用 `透過`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.diving_fabric": "海磷面料",
應用 `布料`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.hazmat_fabric": "毒害隔離織物",
形狀與 `Marine Fabric` 相同，同用 `布料` 就好

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.redstone_grenade": "紅石發信彈",
這邊我不太肯定，但台灣這邊應該是使用 `發射` 或 `訊號發射`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.ice_tnt.keyword": "暴雪人 冰 tnt",
這邊的 `人` 都沒有替換為 `使者`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.beekeeper_fabric": "梭織布",
看 `Fabric` 要統一使用 `布` 還是 `布料`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.barley_block": "大麥垛",
都一樣是 `Bale`，統一譯作 `捆` 即可

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.flax_block": "亞麻垛",
都一樣是 `Bale`，統一譯作 `捆` 即可

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.radish": "小蘿蔔",
從遊戲內圖片看起來，應該是 `櫻桃蘿蔔`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.radish": "小蘿蔔",
從遊戲內圖片看起來，應該是 `櫻桃蘿蔔`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.glowstone_mushroom.keyword": "螢石",
應為螢光石，只在粉型態時稱作 `螢石粉`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.energy_distributor": "RF 分發界面",
`分配介面` 應該比較好

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.chiller_rod_cast": "桿鑄模",
這邊統一使用 `O狀鑄模` 不曉得會不會比較好

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.slot_seal": "欄位卡榫",
感覺可以不用太堅持 `Seal` 原意，能讓玩家清楚知道這是佔位的擋板就好了

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.lumium_detector_rail": "流明探測鐵軌",
`Detector Rail` 台灣這邊翻 `感測鐵軌`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.lumium_powered_rail": "流明充能鐵軌",
`Powered Rail` 台灣這邊翻 `動力鐵軌`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.prismarine_powered_rail": "海磷充能鐵軌",
`Powered Rail` 台灣這邊翻 `動力鐵軌`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.prismarine_detector_rail": "海磷探測鐵軌",
`Detector Rail` 台灣這邊翻 `感測鐵軌`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "entity.thermal.redstone_tnt_minecart": "紅石發信炸藥礦車",
這邊我不太肯定，但台灣這邊應該是使用 `發射` 或 `訊號發射`

2022-11-28 19:38 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.redstone_tnt_minecart": "紅石發信炸藥礦車",
這邊我不太肯定，但台灣這邊應該是使用 `發射` 或 `訊號發射`

2022-11-29 10:29 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.lightning_tnt.desc": "震擊一大片區域，起效時有很大機率伴有雷電。",
我剛對照了英文版的這部分 -> Very likely to bring the thunder.
我想..省略生效部分應該比較符合原文...? -> 很高機率伴有雷電。

2022-11-29 10:31 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "block.thermal.redstone_tnt": "紅石發信炸藥",
這邊我改翻譯為 `紅石訊號炸藥` 這個方塊似乎是爆炸時會大範圍產生紅石訊號 (而且翻譯成6個字與其他tnt比較統一)

2022-11-29 10:36 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.diving_fabric": "海磷面料",
這邊我改翻譯為`防水布料` 似乎比較貼近原文 也符合用途

2022-11-29 10:40 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.hazmat_fabric": "毒害隔離織物",
原文為`Protective Fabric` 但考慮到這個物品製作的套裝 有防護各種異常效果(中毒 凋零 以及火焰傷害) 所以這邊我改翻譯為 `防毒布料`

2022-11-29 10:48 UTC, Jimmy-sheep commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.slot_seal": "欄位卡榫",
呃..那要直翻`佔位擋板`嗎?

2022-11-29 15:14 UTC, StarskyXIII commented on src/main/resources/assets/thermal/lang/zh_tw.json
> +  "item.thermal.slot_seal": "欄位卡榫",
窩噗基道，翻譯基本上都是看譯者當下的喜好為主 XD
如果你認為翻譯沒問題的話，那就保持原樣。

2022-12-12 21:55 UTC, merged